#!/usr/bin/env php
<?php
require __DIR__.'/../vendor/autoload.php';

use Api\Command\InitDb;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new InitDb());
$application->run();
